### ISSUE TITLE
Add Kyber fuzzing to CI

### ISSUE THREAD

**Issue by xvzcf** [cryspen/libcrux#129]
We should clean up the fuzzing code and make it more comprehensive. We could fuzz the Kyber code for a couple of minutes on each PR, and run a longer job where we fuzz the code for an hour or so every night.

**Comment by franziskuskiefer** [comment]
I did a first pass to add fuzzers in franziskus/ml-kem-fuzzing. There seems to be in issue with fuzzers on Linux though.
