### ISSUE TITLE
An F* Spec for Kyber and ML-KEM

### ISSUE THREAD

**Issue by karthikbhargavan** [cryspen/libcrux#144]
We already wrote a spec for Kyber in F*.

We need to refine and extend this spec to more closely match the structure of ML-KEM and be suitable for our proofs.

**Comment by franziskuskiefer** [comment]
This has the wrong priority and is overdue. @karthikbhargavan please update.

**Comment by karthikbhargavan** [comment]
This spec work is done in https://github.com/cryspen/libcrux/pull/475
We will merge this soon and then work more on it if needed for the proofs.

**Comment by karthikbhargavan** [comment]
This is done. Awaiting a hax fix before merging.
https://github.com/cryspen/libcrux/pull/475
