### ISSUE TITLE
C code for Kyber

### ISSUE THREAD

**Issue by karthikbhargavan** [cryspen/libcrux#147]
- [ ] Get it through charon
- [ ] Get it through eurydice
- [ ] Cleanup C code
- [ ] Improve C code
- [x] #145 
- [ ] cryspen/hacl-packages#436
- [x] cryspen/hacl-packages#437

**Comment by franziskuskiefer** [comment]
* unwrap should be doable
* setp_by not clear yet
* match on integers
* enumerate/chunks we may have to rewrite
* Debug could maybe stay (charon with errors as warnings)
