### ISSUE TITLE
Adding a pairing function to Bls12-381

### ISSUE THREAD

**Issue by jtcoolen** [cryspen/libcrux#180]
Hello,

It seems that some Rust APIs lack functions, for example, the BLS12-381 curve doesn't come with a pairing function while the upstream project implements one https://github.com/AU-COBRA/AUCurves/blob/main/src/Hacspec/Curve/Bls.v#L621.

**Comment by spitters** [comment]
Yes, we would like to do that, but currently lack the resources at AU.
You are pointing to the hacspec specification, but as you can see here:
https://github.com/AU-COBRA/AUCurves/blob/main/src/Hacspec/Curve/BlsProof.v
The pairing has not yet been implemented in Coq.

**Comment by jtcoolen** [comment]
Hello @spitters, thanks for the information! I may have a look at it at some point, though I'm a total beginner.
