### ISSUE TITLE
Compilation to wasm

### ISSUE THREAD

**Issue by bshvass** [cryspen/libcrux#225]
Compilation to wasm does not seem to work. I've tried on several machines and with several commands.
The [wasm job](https://github.com/cryspen/libcrux/blob/main/.github/workflows/rust.yml#L121-L138) also seems to have been skipped in recent commits.

Running the command
```bash
cargo build --features wasm --target wasm32-unknown-unknown
```
fails with 
```bash
fatal error: 'string.h' file not found
```
when compiling the files in [sys/hacl/c](https://github.com/cryspen/libcrux/tree/main/sys/hacl/c).

Running the command
```bash
CC=emcc AR=emar cargo build --features wasm --target wasm32-unknown-unknown
```
fails with
```bash
emcc: error: unsupported target: wasm32-unknown-unknown (emcc only supports wasm64-unknown-emscripten and wasm32-unknown-emscripten)
```
Trying with the `wasm32-unknown-emscripten` target simply freezes.

I get similar errors when I try to compile independent packages, which have `libcrux` as dependency, to wasm.

I'm not sure what else to try to get things to compile, but I suspect the issue with the Emscripten compilation.
What is needed to get this working again?

**Comment by franziskuskiefer** [comment]
WASM support is currently pretty limited because a lot of the underlying C code uses raw 64-bit pointers.
We work on integrating a Rust version directly for the legacy C code (see https://github.com/hacl-star/hacl-star/pull/918). But this is work in progress.

Are you interested in a specific algorithm? We could see if we can expose that in the current version.

**Comment by bshvass** [comment]
I was trying to run HMAC compiled to wasm (cf. [this](https://github.com/Concordium/electionguard-rust/pull/10) pull request)

**Comment by franziskuskiefer** [comment]
I think we could make hmac work, SHA2 should be fine. Do you want to take a stab at it? I'm happy to review or give you more concrete pointer if needed.

**Comment by spitters** [comment]
@bshvass this is related to getting the bigints to work in rust
https://github.com/RustCrypto/crypto-bigint/issues/577#issuecomment-2016550215

**Comment by spitters** [comment]
@bshvass What is the status of this?

**Comment by bshvass** [comment]
I haven't had time to look at it yet, but might have some time soon. @franziskuskiefer, I can take a stab at it; did you have any concrete pointers?

**Comment by spitters** [comment]
@bshvass we should probably try with hacl-rs (including hmac and bignum), as it would compile to wasm.
