### ISSUE TITLE
ML-KEM SIMD F* Extraction

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/libcrux#269]
This is blocking #301

**Comment by franziskuskiefer** [comment]
- portable is extracting 
- avx2 is extracting 
- neon needs a dummy for the intrinsics to extract

**Comment by franziskuskiefer** [comment]
Right now F* extraction is broken because of `split_at_mut`.

**Comment by mamonet** [comment]
I saw that `libcrux-ml-kem/src/vector.rs` has dependencies in `libcrux-intrinsics/src` and this issue is about exracting the files in that directory, right?
Also, what kind of problem that `split_at_mut` causes and where I can look at?

**Comment by franziskuskiefer** [comment]
This was fixed in #308 and #311
