### ISSUE TITLE
Run Wycheproof tests on `libcrux-hkdf` and `libcrux-hmac`

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/libcrux#306]
The test vectors are in `tests/wycheproof`, but we don't currently use them.

**Comment by jschneider-bensch** [comment]
Reopening this, since tests are still relevant.

**Comment by franziskuskiefer** [comment]
@keks do you want to close this with the work on #537 ?

**Comment by keks** [comment]
Wycheproof tests for hkdf, hmac and ed25519 are on the PR https://github.com/cryspen/libcrux/pull/659
