### ISSUE TITLE
PSQ PV extraction blockers

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/libcrux#332]
Backend:
- [ ] Robust translation of match pattern syntax, in this case `|` operator
- [ ] Translation of closures (in the case of `map_err()` like here, though, so maybe we don't want to translate that at all)
- [ ] Translation of (byte) string literals (generate constant terms of some kind?)
- [ ] More special function translations for `std` functionality like `expect()`, `map_err()` etc

Engine:
- [ ] Generating interfaces for items from external dependencies

**Comment by franziskuskiefer** [comment]
@jschneider-bensch shall we move this into the code, or is it outdated and we can close it?

**Comment by jschneider-bensch** [comment]
The PSQ code has changed quite a bit since this issue was created, so I'd have to check what the status is now. In any case, maybe let's track this as a hax issue?

**Comment by franziskuskiefer** [comment]
Some of this also seems outdated and seems to work by now. I'm closing this. Let's open something new when we get there.
