### ISSUE TITLE
symcrypt

### ISSUE THREAD

**Issue by epachamo** [cryspen/libcrux#406]
I think [symcrypt](https://github.com/cryspen/libcrux/blob/main/libcrux-ml-kem/c/symcrypt) has accidentally been placed into a submodule. Trying to load libcrux_crypto as a dependency gives me the error: no URL configured for submodule 'libcrux-ml-kem/c/symcrypt'; class=Submodule (17)

**Comment by franziskuskiefer** [comment]
What exactly are you trying to do?
The directory indeed shouldn't be there, it's removed in #407, but it should have no effect.

**Comment by epachamo** [comment]
That worked, thanks!!!! Yeah, you were right, it was cargo that was failing me. I should have provided more detail.
