### ISSUE TITLE
Release ml-kem alpha.2

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/libcrux#424]
Release a new alpha version of the ml-kem crate to include the unpacked APIs.

**Comment by jschneider-bensch** [comment]
With #431 we've released the CAVP crate, since it's a dependency of SHA-3 now.
We saw some semver weirdness (aliasing of `0.0.2-pre.2` and `0.0.2-alpha.2` for `libcrux-platform`) and had not excluded test vectors for the SHA-3 crate so we pushed a `0.0.2-alpha.3` release to fix that.
