### ISSUE TITLE
ML-KEM panic-free/correctness proof analysis

### ISSUE THREAD

**Issue by mamonet** [cryspen/libcrux#447]
This issue analyze the functions of each module in ML-KEM and look for corresponding proofs in `proofs/fstar/extraction-edited/` modules. The functions with no proof found are supposed to have lemmas from scratch that may include panic-free asserts. The modules have tags with roughly estimated delivery date of full correctness proofs.

(Aug 1)
Libcrux_ml_kem.Vector.Portable.Arithmetic.fst (correctness proofs found - extraction-edited/Libcrux.Kem.Kyber.Arithmetic.fst - minimal changes)
Libcrux_ml_kem.Vector.Portable.Compress.fst (correctness proofs found - extraction-edited/Libcrux.Kem.Kyber.Compress.fst - minimal changes)
(Aug 6)
Libcrux_ml_kem.Vector.Portable.Ntt.fst (lax-check)
Libcrux_ml_kem.Vector.Portable.Sampling.fst (lax-check)
(Aug 8)
Libcrux_ml_kem.Vector.Portable.Serialize.fst (lax-check)
(Aug 13)
Libcrux_ml_kem.Ntt.fst (correctness proofs found - extraction-edited/Libcrux.Kem.Kyber.Ntt.fst - medium changes)
Libcrux_ml_kem.Sampling.fst (correctness proofs found - extraction-edited/Libcrux.Kem.Kyber.Sampling.fst - small changes)
Libcrux_ml_kem.Serialize.fst (correctness proofs found - extraction-edited/Libcrux.Kem.Kyber.Serialize.fst - small changes)
(Aug 15)
Libcrux_ml_kem.Ind_cpa.fst (correctness proofs found- extraction-edited/Libcrux.Kem.Kyber.Ind_cpa.fst - medium changes {Unpacked API is not there but still in context})
(Aug 19)
Libcrux_ml_kem.Ind_cca.fst (correctness proofs found - extraction-edited/Libcrux.Kem.Kyber.Kyber.fst - small changes)
(TBD)
Libcrux_ml_kem.Vector.Neon.* (Relative proofs to Libcrux_intrinsics)
Libcrux_ml_kem.Vector.Avx2.* (Relative proofs to Libcrux_intrinsics)

Libcrux_ml_kem.Mlkem512.\*.fst (No proofs needed)
Libcrux_ml_kem.Mlkem768.\*.fst (No proofs needed)
Libcrux_ml_kem.Mlkem1024.*.fst (No proofs needed)

**Comment by karthikbhargavan** [comment]
Closing in favor of https://github.com/cryspen/libcrux/issues/319
