### ISSUE TITLE
Additional malformed input check in `HintBitUnpack()`

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/libcrux#496]
This is in [Algorithm 21, line 9](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.204.pdf#algorithm.21).

**Comment by jschneider-bensch** [comment]
I think we already do this check here: https://github.com/cryspen/libcrux/blob/6a8770c9d9d51b553169e0f2cc8cfd808fc7caa6/libcrux-ml-dsa/src/encoding/signature.rs#L102

**Comment by franziskuskiefer** [comment]
Yes, looks like it.

**Comment by jschneider-bensch** [comment]
Closing this since we are already conformant here.
