### ISSUE TITLE
`ExpandMask` takes output from the beginning of `H`

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/libcrux#498]

**Comment by jschneider-bensch** [comment]
Like #496, it looks to me like we might already be doing this. At least I don't see us skipping a part of the hash output. I'll address the other changes first and use the standard test vectors to check if we're already conformant before looking around more.

**Comment by jschneider-bensch** [comment]
The draft version of `ExpandMask` is as follows:
![expand_mask_draft](https://github.com/user-attachments/assets/e0326cb4-b050-4d17-8690-01af8d1fcbe1)
The final standard specifies:
![expand_mask_final](https://github.com/user-attachments/assets/6f5ce65a-daa6-4df1-9146-309fd1358e5f)
The difference is on line 4, with the final standard taking the first `32*c` bytes of the output of `H` for every loop iteration and the draft taking `32*c` bytes at an offset that grows with the loop iteration count.

For us, this is implemented in [`sample::sample_mask_vector`](https://github.com/cryspen/libcrux/blob/fd43045a84c9f747330800c5b212e3df02e092cd/libcrux-ml-dsa/src/sample.rs#L356-L418). Maybe you can take a look as well @franziskuskiefer, but as far as I can see, we already take the output starting from the beginning for every loop iteration.

**Comment by franziskuskiefer** [comment]
Yes, this is what we do already. The draft version didn't make much sense here I think. For reference: the change was prompted by [this email](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/EkeX7jk9LRI/m/OY3jYaTTAwAJ).
