### ISSUE TITLE
[ML-KEM] Complete portable serialize proofs

### ISSUE THREAD

**Issue by W95Psp** [cryspen/libcrux#515]
We need to:
 - propagate the `[de]serialize_N_int` proofs to `[de]serialize_N`
 - prove them against the spec

**Comment by W95Psp** [comment]
I think this is basically #165

**Comment by franziskuskiefer** [comment]
Shouldn't this be in progress? @W95Psp @karthikbhargavan can you update?

**Comment by W95Psp** [comment]
I think this is basically done, @mamonet has a PR or almost a PR I believe
