### ISSUE TITLE
Add FIPS 203, 204 CAVP test vectors

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/libcrux#520]
At the moment we test ML-KEM and ML-DSA against test vectors that are generated using a spec-like python implementation.
Now that the standards are published, we should add the [official CAVP test vectors](https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files).

**Comment by franziskuskiefer** [comment]
We should also add the wycheproof tests in this or a separate issue (ML-KEM is not yet updated)
- https://github.com/C2SP/wycheproof/pull/112
- https://github.com/C2SP/wycheproof/pull/110

**Comment by franziskuskiefer** [comment]
On branch franziskus/ml-kem-acvp I added started adding some of the test vectors. Feel free to continue on that.

**Comment by jschneider-bensch** [comment]
Took your branch and extended it to encap/decap vectors for ML-KEM in #618
