### ISSUE TITLE
Figure out what needs to be benchmarked

### ISSUE THREAD

**Issue by keks** [cryspen/libcrux#526]
Let's figure out what we need to have on the benchmarks.

- runtime
- stack sizes
- more?

Prompt: https://github.com/cryspen/libcrux/pull/525#discussion_r1727521737

**Comment by franziskuskiefer** [comment]
- binary size

**Comment by franziskuskiefer** [comment]
@keks Shall we close this now that we have a list?

**Comment by keks** [comment]
Yes, let's close this.
