### ISSUE TITLE
[MLKEM] Proofs for avx2 serialize

### ISSUE THREAD

**Issue by W95Psp** [cryspen/libcrux#535]
We need to:
 - replicate the tactic proof I'm doing for https://github.com/cryspen/libcrux/issues/515 and https://github.com/cryspen/libcrux/issues/481
 - prove that correct with respect to the spec
 - Look at 1 4 10 12

**Comment by karthikbhargavan** [comment]
The tactic is done and has been successfully applied on some functions, but needs some debugging for the other serialization functions. This will need to wait till Lucas gets back,

**Comment by franziskuskiefer** [comment]
@W95Psp let us know if you want #518 in before, or leave it out for now.

**Comment by W95Psp** [comment]
I don't really know, but I think that's not important: we don't care about [de]serialize_11 currently, so we can postpone it I believe.

**Comment by karthikbhargavan** [comment]
Merged.
