### ISSUE TITLE
[ML-KEM] Link NTT Proofs to High-Level Spec

### ISSUE THREAD

**Issue by karthikbhargavan** [cryspen/libcrux#566]
The arithmetic and NTT functions need to be properly linked to MLKEM.Spec rather than to localised specifications.

- [x] vector/portable/arithmetic.rs
- [x] vector/portable/ntt.rs
- [x] vector/avx2/arithmetic.rs
- [ ] vector/avx2/ntt.rs
- [x] ntt.rs
- [x] invert_ntt.rs
- [x] polynomial.rs

**Comment by karthikbhargavan** [comment]
Did a big push in this PR: https://github.com/cryspen/libcrux/pull/589
More work coming this week.

**Comment by karthikbhargavan** [comment]
Almost done with this now. Want to do another round of cleanups and merge to main.

**Comment by franziskuskiefer** [comment]
#606

**Comment by karthikbhargavan** [comment]
Closing this in favor of a "merging dev to main" Issue:
https://github.com/cryspen/libcrux/issues/613
