### ISSUE TITLE
SIMD performance regression

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/libcrux#632]
Dropping `.cargo/config.toml`, and thus disabling `build.rustflags = ["-Ctarget-cpu=native"]` has resulted in a significant slowdown of at least the AVX2 version of ML-DSA. We should fix this regression and investigate if other code has also regressed since that was a workplace-wide config.

**Comment by franziskuskiefer** [comment]
Closing as this has generally been fixed.
