### ISSUE TITLE
ML-KEM cg/ extraction broken on big-endian systems

### ISSUE THREAD

**Issue by djmdjm** [cryspen/libcrux#643]
The `libcrux-ml-kem/cg` extraction is broken on big-endian systems. The root cause seems to be [these functions](https://github.com/cryspen/libcrux/blob/13a5dead2cffbec8e7653b532a7e12545801e0a5/libcrux-ml-kem/cg/eurydice_glue.h#L132-L145)  in `eurydice_glue.h`:

```C
static inline void core_num__u64_9__to_le_bytes(uint64_t v, uint8_t buf[8]) {
  memcpy(buf, &v, sizeof(v));
}
static inline uint64_t core_num__u64_9__from_le_bytes(uint8_t buf[8]) {
  uint64_t v;
  memcpy(&v, buf, sizeof(v));
  return v;
}

static inline uint32_t core_num__u32_8__from_le_bytes(uint8_t buf[4]) {
  uint32_t v;
  memcpy(&v, buf, sizeof(v));
  return v;
}
```
which don't do any byte-swapping. We just fixed them in OpenSSH using `endian.h` macros: https://github.com/openssh/openssh-portable/commit/cf3e48ee8ba1beeccddd2f203b558fa102be67a2#diff-36ddc54729ced4a7ff0c5351a9fa6db5229d806a9268fc33f10c61d6cef9811e but it would be nice for them to be fixed upstream.

**Comment by jonathangray** [comment]
https://github.com/AeneasVerif/eurydice/blob/dcfae68c874635956f71d4c05928841b29ad0a8b/include/eurydice_glue.h#L132 has byte swapping.

**Comment by franziskuskiefer** [comment]
Thanks for the report @djmdjm. We minimised the glue here and apparently went a little too far. We'll get this fixed. But I want to have a big endian CPU on CI as well to make sure this doesn't happen again.

**Comment by djmdjm** [comment]
Yes, we've faced the CI problem too - BE architectures are not very common
these days. We're looking at using FreeBSD/ppc64 on qemu

**Comment by franziskuskiefer** [comment]
I added a qemu-based s390x run in #649
