### ISSUE TITLE
Measure stack sizes of select functions using stack painting

### ISSUE THREAD

**Issue by keks** [cryspen/libcrux#695]
Our other methods of measuring stack size report conflicting values, so we need a more reliable way of doing this. The psm::on_stack function helps a lot here. Let's start with the outer API of ML-DSA, and then expand to some of its internal functions. Do this on CI, maybe report the stack sizes as benchmarks to a dashboard. Unfortunately the existing benchmark-to-dashboard thing from Github Actions can't show more than one measured value per graph: https://benchmark-action.github.io/github-action-benchmark/dev/bench/

**Comment by jschneider-bensch** [comment]
Working on this, trying to establish an interactive workflow first, before putting something on CI. For CI, we have https://github.com/cryspen/libcrux/issues/654

**Comment by jschneider-bensch** [comment]
We have some tooling for this now at https://github.com/cryspen/experimental/tree/main/stack-analysis/psm-paint
